// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfleqbxhlcnbttehzqeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbGVxYnhobGNuYnR0ZWh6cWVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTM2MTQsImV4cCI6MjA2MTQyOTYxNH0.1PrJ1nh_dj2hBi5jpkx33cqtIfc-_LF-tW1AI7qPJoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);